version: '3.7'

networks:
  task-manager-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16

volumes:
  kong-db:
    driver: local
  konga-db:
    driver: local
  services-db:
    driver: local

services:
  #######################################
  # Cache server
  #######################################
  cache:
    image: redis:6.2-alpine
    restart: on-failure
    container_name: cache
    networks:
      - task-manager-net
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
  #######################################
  # Message queue broker
  #######################################
  mq-broker:
    image: rabbitmq:3.9-management-alpine
    restart: on-failure
    container_name: mq-broker
    environment:
      RABBITMQ_DEFAULT_VHOST: "/"
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      RABBITMQ_ERLANG_COOKIE: "y5URVMHGodxtifZakNsWpzUUjaO9iONJ"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      task-manager-net:
        ipv4_address: 10.5.0.10
    ports:
      - "15672:15672"
  #######################################
  # Kong database
  #######################################
  kong-database:
    image: postgres:13.5-alpine
    restart: on-failure
    hostname: kong-database
    container_name: kong-database
    volumes:
      - kong-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${KONG_DB_USER}
      POSTGRES_PASSWORD: ${KONG_DB_PASSWORD}
      POSTGRES_DB: ${KONG_DB_DATABASE}
    expose:
      - ${KONG_DB_PORT}
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${KONG_DB_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      task-manager-net:
        ipv4_address: 10.5.0.11
  #######################################
  # Kong: The API Gateway
  #######################################
  kong-gateway:
    build: kong
    restart: on-failure
    hostname: kong-gateway
    container_name: kong-gateway
    volumes:
      - ./kong/ssl:/etc/kong/ssl
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_PORT: ${KONG_DB_PORT}
      KONG_PG_DATABASE: ${KONG_DB_DATABASE}
      KONG_PG_USER: ${KONG_DB_USER}
      KONG_PG_PASSWORD: ${KONG_DB_PASSWORD}
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_PROXY_LISTEN: 0.0.0.0:443 ssl
      KONG_SSL_CERT: /etc/kong/ssl/cert.pem
      KONG_SSL_CERT_KEY: /etc/kong/ssl/key.pem
      KONG_LOG_LEVEL: info
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stdout
    links:
      - kong-database
      - identity-gateway
      - tasks-gateway
    ports:
      - "443:443"
    networks:
      task-manager-net:
        ipv4_address: 10.5.0.12
    healthcheck:
      test: [ "CMD", "kong", "health" ]
      interval: 10s
      timeout: 10s
      retries: 10
  #######################################
  # MariaDB: Konga database
  #######################################
  konga-database:
    image: mariadb:10.7.1-focal
    container_name: konga-database
    restart: on-failure
    volumes:
      - konga-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${KONGA_ROOT_PASSWORD}
      MYSQL_USER: ${KONGA_DB_USER}
      MYSQL_PASSWORD: ${KONGA_DB_PASSWORD}
      MYSQL_DATABASE: ${KONGA_DB_DATABASE}
    expose:
      - ${KONGA_DB_PORT}
    networks:
      task-manager-net:
        ipv4_address: 10.5.0.13
  #######################################
  # Konga: Kong Admin UI
  #######################################
  konga:
    build: konga
    container_name: konga
    restart: on-failure
    environment:
      TOKEN_SECRET: 55NB8SbgeAnCtsQAJPShDg7vGTagRqw8
      DB_ADAPTER: mysql
      DB_URI: "mysql://${KONGA_DB_USER}:${KONGA_DB_PASSWORD}@konga-database:${KONGA_DB_PORT}/${KONGA_DB_DATABASE}"
      KONGA_HOOK_TIMEOUT: 120000
      KONGA_LOG_LEVEL: info
      NODE_ENV: production
    links:
      - konga-database
      - kong-gateway
    networks:
      task-manager-net:
        ipv4_address: 10.5.0.14
    ports:
      - "1337:1337"
  #######################################
  # Services database
  #######################################
  services-database:
    image: mariadb:10.7.1-focal
    restart: on-failure
    container_name: services-database
    volumes:
      - services-db:/var/lib/mysql
      - ./init-databases:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_USER}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    expose:
      - ${MYSQL_PORT}
    ports:
      - "23306:${MYSQL_PORT}"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    networks:
      task-manager-net:
        ipv4_address: 10.5.0.15
  #######################################
  # Identity service
  #######################################
  identity-gateway:
    build:
      context: .
      dockerfile: nginx/Dockerfile
      args:
        SERVICE: identity
    container_name: identity-gateway
    restart: on-failure
    volumes:
      - ./logs:/var/log/nginx
      - ../microservices/identity:/var/www/html
    networks:
      - task-manager-net
    links:
      - identity
    ports:
      - "8088:443"
  identity:
    build: php/fpm
    container_name: identity
    restart: on-failure
    volumes:
      - ../microservices/identity:/var/www/html
      - ../microservices/identity/supervisor-consumers.conf:/etc/supervisor/conf.d/supervisor-consumers.conf
    environment:
      DATABASE_URL: "mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@services-database:${MYSQL_PORT}/identity_db?serverVersion=mariadb-10.7.1"
      MESSENGER_TRANSPORT_DSN: "amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@mq-broker:5672/%2f/messages"
      REDIS_DSN: "redis://cache"
      APP_ENV: "${APP_ENV}"
    networks:
      task-manager-net:
        ipv4_address: 10.5.0.16
    expose:
      - 9000
      - 9013 #xdebug
    links:
      - services-database
      - mq-broker
      - cache
  #######################################
  # API admin service
  #######################################
  api-admin:
    build: php/cli
    container_name: api-admin
    restart: on-failure
    tty: true
    volumes:
      - ../microservices/api-admin:/usr/src/app
      - ../microservices/api-admin/supervisor-consumers.conf:/etc/supervisor/conf.d/supervisor-consumers.conf
    environment:
      DATABASE_URL: "mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@services-database:${MYSQL_PORT}/api_admin_db?serverVersion=mariadb-10.7.1"
      MESSENGER_TRANSPORT_DSN: "amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@mq-broker:5672/%2f/messages"
      APP_ENV: "${APP_ENV}"
      API_GATEWAY_ADMIN_URL: "http://kong-gateway:8001"
    networks:
      task-manager-net:
        ipv4_address: 10.5.0.17
    expose:
      - 9013 #xdebug
    links:
      - services-database
      - mq-broker
      - kong-gateway
  #######################################
  # Tasks service
  #######################################
  tasks-gateway:
    build:
      context: .
      dockerfile: nginx/Dockerfile
      args:
        SERVICE: tasks
    container_name: tasks-gateway
    restart: on-failure
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/tasks/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs:/var/log/nginx
      - ../microservices/tasks:/var/www/html
    networks:
      - task-manager-net
    links:
      - tasks
  tasks:
    build: php/fpm
    container_name: tasks
    restart: on-failure
    volumes:
      - ../microservices/tasks:/var/www/html
      - ../microservices/tasks/supervisor-consumers.conf:/etc/supervisor/conf.d/supervisor-consumers.conf
    working_dir: /var/www/html
    environment:
      DATABASE_URL: "mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@services-database:${MYSQL_PORT}/tasks_db?serverVersion=mariadb-10.7.1"
      REDIS_DSN: "redis://cache"
      APP_ENV: "${APP_ENV}"
    networks:
      task-manager-net:
        ipv4_address: 10.5.0.18
    links:
      - services-database
      - mq-broker
      - cache
    expose:
      - 9000
      - 9013 #xdebug
